spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/linkcentral?useUnicode=true&serverTimezone=Asia/Seoul&autoReconnect=true
    username: seok
    password: 1234
  session:
    store-type: jdbc
    jdbc.initialize-schema: always
  hiddenmethod:
    filter:
      enabled: true
  profiles:
    include: oauth
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: alstjr706@gmail.com
    password: ${MAIL}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
jwt:
 secret: ${JWT_SECRET:ZGVmYXVsdF9zZWNyZXRfdmFsdWVfZGVmYXVsdF9zZWNyZXRfdmFsdWVfZGVmYXVsdF9zZWNyZXRfdmFsdWUK}

logging:
  level:
    org:
      hibernate:
        type:
          # 쿼리에 물음표로 출력되는 바인드 파라미터 출력
          descriptor.sql: trace
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
cloud:
  aws:
    s3:
      bucket: mingseokbucket
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
    credentials:
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_KEY}